# Generated by Django 2.2.25 on 2022-05-24 08:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookJournalBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('decription', models.CharField(max_length=512)),
                ('created_at', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bookjournalbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.BookJournalBase')),
                ('num_pages', models.IntegerField()),
                ('genre', models.PositiveSmallIntegerField(choices=[(0, 'HORROR'), (1, 'ROMATIC'), (2, 'DETECTIVE'), (3, 'MAFIA')])),
            ],
            bases=('api.bookjournalbase',),
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('bookjournalbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.BookJournalBase')),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'BULLET'), (1, 'FOOD'), (2, 'TRAVEL'), (3, 'SPORT')])),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('api.bookjournalbase',),
        ),
    ]
